version: "3.8"
services:

  rabbitmq: 
    build:
      context: ./rabbit
      dockerfile: dockerfile
    container_name: rabbit
    expose: 
      - "5672"
      - "1883"
    ports: 
      - "5672:5672"
      - "1883:1883"
    networks: 
      meseros-net:
        aliases: 
          - rabbitmq      

networks:
  meseros-net:
    name: meseros-net
    driver: bridge
    ipam: 
      config: 
        - subnet: 172.16.238.0/24
